version: '3.1'

services:
  nginx:
    container_name: mstaff-micro__front-symfo-1__prod__nginx
    image: nginx:alpine
    working_dir: /application
    depends_on:
      - 'php-fpm'
    volumes:
      - './docker/prod/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'

  php-fpm:
    container_name: mstaff-micro__front-symfo-1__prod__php-fpm
    build: docker/prod/php-fpm
    working_dir: /application
    volumes:
      - '.:/application'
      - './docker/prod/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'

networks:
  mstaff-micro.network:
    external: true